# Basic dependabot.yml file with
# minimum configuration for nuget
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/source/coordinator/GreenEnergyHub.Aggregation.Application"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/coordinator/GreenEnergyHub.Aggregation.Coordinator"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/coordinator/GreenEnergyHub.Aggregation.Core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/coordinator/GreenEnergyHub.Aggregation.DatabaseMigration"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/coordinator/GreenEnergyHub.Aggregation.Domain"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/coordinator/GreenEnergyHub.Aggregation.Infrastructure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "nuget"
    directory: "/source/coordinator/GreenEnergyHub.Aggregation.Tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0