// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Energinet.DataHub.Aggregations.Infrastructure.Persistence
{
    public partial class Charge
    {
        public Guid RowId { get; set; }
        public string ChargeKey { get; set; }
        public string ChargeId { get; set; }
        public int ChargeType { get; set; }
        public string ChargeOwnerId { get; set; }
        public int Resolution { get; set; }
        public bool ChargeTax { get; set; }
        public string Currency { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
    }
}