// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Energinet.DataHub.Aggregations.Infrastructure.Persistence
{
    public partial class ChargePrice
    {
        public Guid RowId { get; set; }
        public string ChargeKey { get; set; }
        public decimal ChargePrice1 { get; set; }
        public DateTime Time { get; set; }
    }
}