// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Energinet.DataHub.Aggregations.Infrastructure.Persistence
{
    public partial class EsBrpRelation
    {
        public Guid RowId { get; set; }
        public string EnergySupplierId { get; set; }
        public string BalanceResponsibleId { get; set; }
        public string GridArea { get; set; }
        public int MeteringPointType { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
    }
}