// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Energinet.DataHub.Aggregations.Infrastructure.Persistence
{
    public partial class MeteringPoint
    {
        public Guid RowId { get; set; }
        public string MeteringPointId { get; set; }
        public int MeteringPointType { get; set; }
        public int? SettlementMethod { get; set; }
        public string GridArea { get; set; }
        public int ConnectionState { get; set; }
        public int Resolution { get; set; }
        public string InGridArea { get; set; }
        public string OutGridArea { get; set; }
        public int MeteringMethod { get; set; }
        public string ParentMeteringPointId { get; set; }
        public int Unit { get; set; }
        public string Product { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
    }
}