name: 'Obtain Databricks Workspace ID and Url'
description: 'Obtains Databricks Workspace ID and Url and provides those as output. Note: expects Azure CLI and Python to be installed on a runner.'
  workspace-url: 
    description: "Databricks Workspace Url"
    value: ${{ steps.obtain-db-id-url.outputs.workspace-url }}
runs:
  using: "composite"
  steps: 
    - id: obtain-db-id-url
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt 
        res=$(az databricks workspace show -g ${{ matrix.environment.long }} -n "dbw-${{ env.PROJECT_NAME }}-${{ env.ORGANISATION_NAME }}-${{ matrix.environment.short  }}")
        WORKSPACE_URL=$(echo $res | python -c "import sys, json; print(json.load(sys.stdin)['workspaceUrl'])")
        echo $WORKSPACE_URL
        echo "::set-output name=workspace-url::$(echo $WORKSPACE_URL)"
      shell: bash