# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@6.0.0

  dotnet_solution_coordinator_ci:
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-solution-ci.yml@6.0.0
    with:
      SOLUTION_FILE_PATH: 'source/coordinator/Energinet.DataHub.Aggregation.Coordinator.sln'
      DOTNET_VERSION: '5.0.202'
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_SPN_ID: ${{ secrets.AZURE_SPN_ID }}
      AZURE_SPN_SECRET: ${{ secrets.AZURE_SPN_SECRET }}
      AZURE_KEYVAULT_URL: ${{ secrets.AZURE_KEYVAULT_URL }}

  dotnet_solution_integration_event_listener_ci:
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-solution-ci.yml@6.0.0
    with:
      SOLUTION_FILE_PATH: 'source/IntegrationEventListener/Energinet.DataHub.Aggregations.sln'
      DOTNET_VERSION: '5.0.202'
      USE_AZURE_FUNCTIONS_TOOLS: true
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_SPN_ID: ${{ secrets.AZURE_SPN_ID }}
      AZURE_SPN_SECRET: ${{ secrets.AZURE_SPN_SECRET }}
      AZURE_KEYVAULT_URL: ${{ secrets.AZURE_KEYVAULT_URL }}

  databricks_ci:
    uses: Energinet-DataHub/.github/.github/workflows/python-ci-test-and-coverage.yml@6.0.1
    with:
      PATH_STATIC_CHECKS: './source'
      IGNORE_ERRORS_AND_WARNING_FLAKE8: 'E501,F401,E402,W503,E122,E123,E126,F811'
      TEST_REPORT_PATH: ./source/databricks/tests/coverage.json

  terraform_validate_main:
    uses: Energinet-DataHub/.github/.github/workflows/terraform-validate.yml@6.0.0
    with:
      TERRAFORM_WORKING_DIR_PATH: "./build/primary/main"
      TERRAFORM_VERSION: "1.1.6"

  terraform_validate_streaming_cluster:
    uses: Energinet-DataHub/.github/.github/workflows/terraform-validate.yml@6.0.0
    with:
      TERRAFORM_WORKING_DIR_PATH: "./build/databricks_streaming_cluster"
      TERRAFORM_VERSION: "1.1.6"

  terraform_validate_aggregations_cluster:
    uses: Energinet-DataHub/.github/.github/workflows/terraform-validate.yml@6.0.0
    with:
      TERRAFORM_WORKING_DIR_PATH: "./build/databricks_aggregations_cluster"
      TERRAFORM_VERSION: "1.1.6"

  coordinator_ci:
    needs:
      [
        ci_base,
        terraform_validate_main,
        terraform_validate_streaming_cluster,
        terraform_validate_aggregations_cluster,
      ]
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-create-function-artifact.yml@6.0.0
    with:
      CSPROJ_FILE_PATH: "source/coordinator/Energinet.DataHub.Aggregation.Coordinator.CoordinatorFunction/Energinet.DataHub.Aggregation.Coordinator.CoordinatorFunction.csproj"
      DOTNET_VERSION: "5.0.202"
      ARTIFACT_NAME: coordinator

  integration_event_listener_ci:
    needs:
      [
        ci_base,
        terraform_validate_main,
        terraform_validate_streaming_cluster,
        terraform_validate_aggregations_cluster,
      ]
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-create-function-artifact.yml@6.0.0
    with:
      CSPROJ_FILE_PATH: "source/IntegrationEventListener/source/Energinet.DataHub.Aggregations.IntegrationEventListener/Energinet.DataHub.Aggregations.IntegrationEventListener.csproj"
      DOTNET_VERSION: "5.0.202"
      ARTIFACT_NAME: integration_event_listener

  wheel_ci:
    needs:
      [
        ci_base,
        terraform_validate_main,
        terraform_validate_streaming_cluster,
        terraform_validate_aggregations_cluster,
      ]
    uses: Energinet-DataHub/.github/.github/workflows/python-wheel-ci.yml@6.0.0
    with:
      PYHTON_VERSION: "3.8.6"
      ARCHITECTURE: "x64"
      WHEEL_WORKING_DIRECTORY: "./source/databricks"
      ARTIFACT_NAME: "wheel"
      ARTIFACT_PATH: "./source/databricks/dist"

  coordinator_database_migration_ci:
    needs:
      [
        ci_base,
        terraform_validate_main,
        terraform_validate_streaming_cluster,
        terraform_validate_aggregations_cluster,
      ]
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-create-function-artifact.yml@6.0.0
    with:
      CSPROJ_FILE_PATH: "source/coordinator/Energinet.DataHub.Aggregation.Coordinator.DatabaseMigration/Energinet.DataHub.Aggregation.Coordinator.DatabaseMigration.csproj"
      DOTNET_VERSION: "5.0"
      ARTIFACT_NAME: coordinatordatabasemigration

  masterdata_database_migration_ci:
    needs:
      [
        ci_base,
        terraform_validate_main,
        terraform_validate_streaming_cluster,
        terraform_validate_aggregations_cluster,
      ]
    uses: Energinet-DataHub/.github/.github/workflows/dotnet-create-function-artifact.yml@5.0.5
    with:
      CSPROJ_FILE_PATH: "source/IntegrationEventListener/Energinet.DataHub.Aggregations.DatabaseMigration/Energinet.DataHub.Aggregations.DatabaseMigration.csproj"
      DOTNET_VERSION: "5.0"
      ARTIFACT_NAME: masterdatadatabasemigration

  create_prerelease:
    needs: [coordinator_ci, integration_event_listener_ci, wheel_ci, masterdata_database_migration_ci, coordinator_database_migration_ci]
    uses: Energinet-DataHub/.github/.github/workflows/create-prerelease.yml@6.0.0
    with:
      CALLER_REPOSITORY_PATH: Energinet-DataHub/geh-aggregations
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
