name: CodeCov
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: 'Collect coverage'
      run: |
        cd source/databricks
        pip install coverage pytest pyspark pandas
        coverage run --branch -m pytest tests/
    - name: 'Upload coverage'
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true

      
