name: CodeCov
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: Skip check
      id: python_skip_check
      uses: fkirc/skip-duplicate-actions@v1.4.0
      with:
        github_token: ${{ github.token }}
        paths: '["**.py"]'

    - name: 'Test and collect coverage'
      if: ${{ steps.python_skip_check.outputs.should_skip == 'false' }}
      uses: ./.github/actions/databricks-unit-test
      
