# Copyright 2020 Energinet DataHub A/S
 #
 # Licensed under the Apache License, Version 2.0 (the "License2");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
name: Code coverage
on:
   push:
     branches:
       - main
   pull_request:
     branches:
       - main
   workflow_dispatch: {}

env:
  DOTNET_VERSION: '3.1'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip_python: ${{ steps.python_skip_check.outputs.should_skip }}
      should_skip_dotnet: ${{ steps.dotnet_skip_check.outputs.should_skip }}
    steps:
      - name: Should skip python?
        id: python_skip_check
        uses: fkirc/skip-duplicate-actions@v1.4.0
        with:
          github_token: ${{ github.token }}
          paths: '[
            "codecov.yml",
             ".github/workflows/codecov-ci.yml",
             "source/databricks/geh_stream/**"
          ]'
      - name: Should skip dotnet?
        id: dotnet_skip_check
        uses: fkirc/skip-duplicate-actions@v1.4.0
        with:
          github_token: ${{ github.token }}
          paths: '[
            "codecov.yml",
             ".github/workflows/codecov-ci.yml",
             "source/coordinator/**"
          ]'
  
  collect_coverage_python:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip_python != 'true' || github.ref == 'refs/heads/main' }}
    name: Collect code coverage Python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: 'Collect coverage'
      run: |
        cd source/databricks
        pip install coverage pytest-cov pyspark pandas wheel requests
        python -m pytest --junitxml=test-reports/test-results.xml --cov=./ --cov-report=xml
    - name: 'Upload coverage'
      uses: codecov/codecov-action@v2
      with:
        flags: unit-python
        fail_ci_if_error: true
  
  collect_coverage_dotnet:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip_dotnet != 'true' || github.ref == 'refs/heads/main' }}
    name: Collect code coverage .NET
    runs-on: ubuntu-latest
    strategy:
       matrix:
         project: [
           source/coordinator/GreenEnergyHub.Aggregation.Tests/GreenEnergyHub.Aggregation.Tests.csproj
         ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup .NET ${{ env.DOTNET_VERSION }} environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Collect coverage
        run: dotnet test ${{ matrix.project }} --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          flags: unit-dotnet
          fail_ci_if_error: true
          verbose: true
