# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: 1 - Infrastructure CD

on:
  push:
    branches:
      - main
    paths:
      - build/infrastructure/**
      - build/modules/**
      - .github/workflows/infrastructure-cd.yml
  workflow_dispatch: {}
env:
  ORGANISATION_NAME: endk
  PROJECT_NAME: aggregations

jobs:
  infra_deploy_development:
    name: Deploy infrastructure to rg-DataHub-Aggregations-U
    runs-on: ubuntu-latest
    environment:
      name: rg-DataHub-Aggregations-U
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_wrapper: false
          terraform_version: 0.14.10

      - name: Terraform CD
        uses: ./.github/actions/terraform-cd
        with:
          SECRETS_SHARED_RESOURCES_KEYVAULT_NAME: ${{ secrets.SHAREDRESOURCES_KEYVAULT_NAME }}
          SECRETS_SHARED_RESOURCES_RESOURCE_GROUP_NAME: ${{ secrets.SHAREDRESOURCES_RESOURCE_GROUP_NAME }}
          SECRETS_PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          SECRETS_TENANT_ID: ${{ secrets.TENANT_ID }}
          SECRETS_SPN_ID: ${{ secrets.SPN_ID }}
          SECRETS_SPN_OBJECT_ID: ${{ secrets.SPN_OBJECT_ID }}
          SECRETS_SPN_SECRET: ${{ secrets.SPN_SECRET }}
          SECRETS_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          SECRETS_GRID_LOSS_SYS_COR_PATH: ${{ secrets.GRID_LOSS_SYS_COR_PATH }}
          SECRETS_INPUT_PATH: ${{ secrets.INPUT_PATH }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
          ENVIRONMENT_SHORT: u
          ENVIRONMENT_LONG: rg-DataHub-Aggregations-U
          ENVIRONMENT_NAME: Development
          TERRAFORM_BACKEND_FILE_PATH: "./build/infrastructure/backend.tf"

      - name: Azure key vault - Get Secrets
        uses: Azure/get-keyvault-secrets@v1.2
        with:
          keyvault: "kvsharedresendku"
          secrets: 'SHARED-RESOURCES-DB-ADMIN-NAME,SHARED-RESOURCES-DB-ADMIN-PASSWORD'  # comma separated list of secret keys that need to be fetched from the Key Vault 
        id: myGetSecretAction

      - name: DB Migrations
        run: dotnet run --project ./source/coordinator/GreenEnergyHub.Aggregation.DatabaseMigration/ --configuration Release -- "Server=tcp:sqlsrv-sharedres-endk-u.database.windows.net,1433;Initial Catalog=sqldb-aggregation-metadata;Persist Security Info=False;User ID=${{ steps.myGetSecretAction.outputs.SHARED-RESOURCES-DB-ADMIN-NAME }};Password=${{ steps.myGetSecretAction.outputs.SHARED-RESOURCES-DB-ADMIN-PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        

  infra_deploy_test:
    name: Deploy infrastructure to rg-DataHub-Aggregations-T
    needs: infra_deploy_development
    runs-on: ubuntu-latest
    environment:
      name: rg-DataHub-Aggregations-T
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_wrapper: false
          terraform_version: 0.14.10

      - name: Terraform CD
        uses: ./.github/actions/terraform-cd
        with:
          SECRETS_SHARED_RESOURCES_KEYVAULT_NAME: ${{ secrets.SHAREDRESOURCES_KEYVAULT_NAME }}
          SECRETS_SHARED_RESOURCES_RESOURCE_GROUP_NAME: ${{ secrets.SHAREDRESOURCES_RESOURCE_GROUP_NAME }}
          SECRETS_PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          SECRETS_TENANT_ID: ${{ secrets.TENANT_ID }}
          SECRETS_SPN_ID: ${{ secrets.SPN_ID }}
          SECRETS_SPN_OBJECT_ID: ${{ secrets.SPN_OBJECT_ID }}
          SECRETS_SPN_SECRET: ${{ secrets.SPN_SECRET }}
          SECRETS_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          SECRETS_GRID_LOSS_SYS_COR_PATH: ${{ secrets.GRID_LOSS_SYS_COR_PATH }}
          SECRETS_INPUT_PATH: ${{ secrets.INPUT_PATH }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
          ENVIRONMENT_SHORT: t
          ENVIRONMENT_LONG: rg-DataHub-Aggregations-T
          ENVIRONMENT_NAME: Test
          TERRAFORM_BACKEND_FILE_PATH: "./build/infrastructure/backend.tf"

      - name: Azure key vault - Get Secrets
        uses: Azure/get-keyvault-secrets@v1.2
        with:
          keyvault: "kvsharedresendkt"
          secrets: 'SHARED-RESOURCES-DB-ADMIN-NAME,SHARED-RESOURCES-DB-ADMIN-PASSWORD'  # comma separated list of secret keys that need to be fetched from the Key Vault 
        id: myGetSecretAction

      - name: DB Migrations
        run: dotnet run --project ./source/coordinator/GreenEnergyHub.Aggregation.DatabaseMigration/ --configuration Release -- "Server=tcp:sqlsrv-sharedres-endk-t.database.windows.net,1433;Initial Catalog=sqldb-aggregation-metadata;Persist Security Info=False;User ID=${{ steps.myGetSecretAction.outputs.SHARED-RESOURCES-DB-ADMIN-NAME }};Password=${{ steps.myGetSecretAction.outputs.SHARED-RESOURCES-DB-ADMIN-PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

  infra_deploy_preprod:
    name: Deploy infrastructure to rg-DataHub-Aggregations-B
    needs: infra_deploy_test
    runs-on: ubuntu-latest
    environment:
      name: rg-DataHub-Aggregations-B
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_wrapper: false
          terraform_version: 0.14.10

      - name: Terraform CD
        uses: ./.github/actions/terraform-cd
        with:
          SECRETS_SHARED_RESOURCES_KEYVAULT_NAME: ${{ secrets.SHAREDRESOURCES_KEYVAULT_NAME }}
          SECRETS_SHARED_RESOURCES_RESOURCE_GROUP_NAME: ${{ secrets.SHAREDRESOURCES_RESOURCE_GROUP_NAME }}
          SECRETS_PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          SECRETS_TENANT_ID: ${{ secrets.TENANT_ID }}
          SECRETS_SPN_ID: ${{ secrets.SPN_ID }}
          SECRETS_SPN_OBJECT_ID: ${{ secrets.SPN_OBJECT_ID }}
          SECRETS_SPN_SECRET: ${{ secrets.SPN_SECRET }}
          SECRETS_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          SECRETS_GRID_LOSS_SYS_COR_PATH: ${{ secrets.GRID_LOSS_SYS_COR_PATH }}
          SECRETS_INPUT_PATH: ${{ secrets.INPUT_PATH }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
          ENVIRONMENT_SHORT: b
          ENVIRONMENT_LONG: rg-DataHub-Aggregations-B
          ENVIRONMENT_NAME: Preprod
          TERRAFORM_BACKEND_FILE_PATH: "./build/infrastructure/backend.tf"

      - name: Azure key vault - Get Secrets
        uses: Azure/get-keyvault-secrets@v1.2
        with:
          keyvault: "kvsharedresendkb"
          secrets: 'SHARED-RESOURCES-DB-ADMIN-NAME,SHARED-RESOURCES-DB-ADMIN-PASSWORD'  # comma separated list of secret keys that need to be fetched from the Key Vault 
        id: myGetSecretAction

      - name: DB Migrations
        run: dotnet run --project ./source/coordinator/GreenEnergyHub.Aggregation.DatabaseMigration/ --configuration Release -- "Server=tcp:sqlsrv-sharedres-endk-b.database.windows.net,1433;Initial Catalog=sqldb-aggregation-metadata;Persist Security Info=False;User ID=${{ steps.myGetSecretAction.outputs.SHARED-RESOURCES-DB-ADMIN-NAME }};Password=${{ steps.myGetSecretAction.outputs.SHARED-RESOURCES-DB-ADMIN-PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

  infra_deploy_prod:
    name: Deploy infrastructure to rg-DataHub-Aggregations-P
    needs: infra_deploy_preprod
    runs-on: ubuntu-latest
    environment:
      name: rg-DataHub-Aggregations-P
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_wrapper: false
          terraform_version: 0.14.10

      - name: Terraform CD
        uses: ./.github/actions/terraform-cd
        with:
          SECRETS_SHARED_RESOURCES_KEYVAULT_NAME: ${{ secrets.SHAREDRESOURCES_KEYVAULT_NAME }}
          SECRETS_SHARED_RESOURCES_RESOURCE_GROUP_NAME: ${{ secrets.SHAREDRESOURCES_RESOURCE_GROUP_NAME }}
          SECRETS_PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          SECRETS_TENANT_ID: ${{ secrets.TENANT_ID }}
          SECRETS_SPN_ID: ${{ secrets.SPN_ID }}
          SECRETS_SPN_OBJECT_ID: ${{ secrets.SPN_OBJECT_ID }}
          SECRETS_SPN_SECRET: ${{ secrets.SPN_SECRET }}
          SECRETS_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          SECRETS_GRID_LOSS_SYS_COR_PATH: ${{ secrets.GRID_LOSS_SYS_COR_PATH }}
          SECRETS_INPUT_PATH: ${{ secrets.INPUT_PATH }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
          ENVIRONMENT_SHORT: p
          ENVIRONMENT_LONG: rg-DataHub-Aggregations-P
          ENVIRONMENT_NAME: Prod
          TERRAFORM_BACKEND_FILE_PATH: "./build/infrastructure/backend.tf"
          
      - name: Azure key vault - Get Secrets
        uses: Azure/get-keyvault-secrets@v1.2
        with:
          keyvault: "kvsharedresendkp"
          secrets: 'SHARED-RESOURCES-DB-ADMIN-NAME,SHARED-RESOURCES-DB-ADMIN-PASSWORD'  # comma separated list of secret keys that need to be fetched from the Key Vault 
        id: myGetSecretAction

      - name: DB Migrations
        run: dotnet run --project ./source/coordinator/GreenEnergyHub.Aggregation.DatabaseMigration/ --configuration Release -- "Server=tcp:sqlsrv-sharedres-endk-p.database.windows.net,1433;Initial Catalog=sqldb-aggregation-metadata;Persist Security Info=False;User ID=${{ steps.myGetSecretAction.outputs.SHARED-RESOURCES-DB-ADMIN-NAME }};Password=${{ steps.myGetSecretAction.outputs.SHARED-RESOURCES-DB-ADMIN-PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
